name: sen331_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/apple.png
    - assets/img/cloth1.png
    - assets/img/cloth2.png
    - assets/img/cloth3.png
    - assets/img/sold.png
    - assets/img/sold1.png
    - assets/img/sold3.png
    - assets/img/sold4.png
    - assets/img/hero.png
    - assets/img/catalog1.png
    - assets/img/catalog2.png
    - assets/img/catalog3.png
    - assets/img/catalog4.png
    - assets/img/catalog5.png
    - assets/img/cart1.png
    - assets/img/cart2.png
    - assets/img/cart3.png
    - assets/img/applepay.png
    - assets/img/mastercard.png
    - assets/img/paypal.png
    - assets/img/creditcard.png
    - assets/icons/globe.png
    - assets/icons/about.png
   
